name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    name: Build on manylinux2014
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
          pip install pyinstaller requests

      - name: Build binary
        run: |
          pyinstaller --onefile src/cliprophesy/main.py
          mv dist/main dist/cliprophesy-linux

      - uses: actions/upload-artifact@v4
        with:
          name: cliprophesy
          path: dist/cliprophesy-linux

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller requests

      - name: Build binary
        run: |
          pyinstaller --onefile src/cliprophesy/main.py
          mv dist/main dist/cliprophesy-macos

      - uses: actions/upload-artifact@v4
        with:
          name: cliprophesy
          path: dist/cliprophesy-macos

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cliprophesy
          path: ./linux

      - uses: actions/download-artifact@v4
        with:
          name: cliprophesy
          path: ./macos

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./linux/cliprophesy
            ./macos/cliprophesy
